default: all
all:
	gcc -Wall -std=c99 -o LinkedListStack LinkedListStack.c
	gcc -Wall -std=c99 -o LinkedListQueue LinkedListQueue.c
	gcc -Wall -std=c99 -o LinkedListDeque LinkedListDeque.c
	gcc -Wall -std=c99 -o LinkedListDeque LinkedListBag.c